# Generated by Django 5.0.6 on 2024-06-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSAF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fechaNacimiento',
        ),
    ]
